ERROR 2024-04-02 11:04:03,765 log 19512 19612 Internal Server Error: /api/download-and-read-source-json/
Traceback (most recent call last):
  File "C:\nal_adc_support\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\nal_adc_support\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\nal_adc_support\env\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\nal_adc_support\env\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\nal_adc_support\env\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\nal_adc_support\env\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\nal_adc_support\env\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\nal_adc_support\env\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\nal_adc_support\env\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "C:\nal_adc_support\ADC\api\read_source_json_and_write_in_file.py", line 85, in read_json_and_write_in_file
    save_to_file(filter_data(data, bureauCode))
  File "C:\nal_adc_support\ADC\api\read_source_json_and_write_in_file.py", line 63, in save_to_file
    with open(file_name,'w') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\nal_adc_support\\ADC\\stakes\\USDA-ERS-02580.json'
ERROR 2024-04-02 11:04:03,768 basehttp 19512 19612 "GET /api/download-and-read-source-json/ HTTP/1.1" 500 117930
ERROR 2024-04-02 11:05:44,501 log 19512 17908 Internal Server Error: /api/download-and-read-source-json/
Traceback (most recent call last):
  File "C:\nal_adc_support\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\nal_adc_support\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\nal_adc_support\env\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\nal_adc_support\env\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\nal_adc_support\env\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\nal_adc_support\env\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\nal_adc_support\env\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\nal_adc_support\env\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\nal_adc_support\env\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "C:\nal_adc_support\ADC\api\read_source_json_and_write_in_file.py", line 85, in read_json_and_write_in_file
    save_to_file(filter_data(data, bureauCode))
  File "C:\nal_adc_support\ADC\api\read_source_json_and_write_in_file.py", line 63, in save_to_file
    with open(file_name,'w') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\nal_adc_support\\ADC\\stakes\\USDA-ERS-02580.json'
ERROR 2024-04-02 11:05:44,502 basehttp 19512 17908 "GET /api/download-and-read-source-json/ HTTP/1.1" 500 117778
ERROR 2024-04-02 11:08:59,621 log 15328 13016 Internal Server Error: /api/download-and-read-source-json/
Traceback (most recent call last):
  File "C:\nal_adc_support\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\nal_adc_support\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\nal_adc_support\env\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\nal_adc_support\env\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\nal_adc_support\env\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\nal_adc_support\env\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\nal_adc_support\env\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\nal_adc_support\env\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\nal_adc_support\env\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "C:\nal_adc_support\ADC\api\read_source_json_and_write_in_file.py", line 87, in read_json_and_write_in_file
    save_to_file(filter_data(data, bureauCode))
  File "C:\nal_adc_support\ADC\api\read_source_json_and_write_in_file.py", line 63, in save_to_file
    with open(file_name,'w') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\nal_adc_support\\ADC\\stakes\\USDA-ERS-02580.json'
ERROR 2024-04-02 11:08:59,623 basehttp 15328 13016 "GET /api/download-and-read-source-json/ HTTP/1.1" 500 117918
ERROR 2024-04-02 11:10:46,226 log 18036 20028 Internal Server Error: /api/download-and-read-source-json/
Traceback (most recent call last):
  File "C:\nal_adc_support\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\nal_adc_support\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\nal_adc_support\env\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\nal_adc_support\env\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\nal_adc_support\env\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\nal_adc_support\env\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\nal_adc_support\env\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\nal_adc_support\env\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\nal_adc_support\env\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "C:\nal_adc_support\ADC\api\read_source_json_and_write_in_file.py", line 86, in read_json_and_write_in_file
    save_to_file(filter_data(data, bureauCode))
  File "C:\nal_adc_support\ADC\api\read_source_json_and_write_in_file.py", line 64, in save_to_file
    with open(file_name,'w') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\nal_adc_support\\ADC\\stakes\\USDA-ERS-02580.json'
ERROR 2024-04-02 11:10:50,408 log 18036 21444 Internal Server Error: /api/download-and-read-source-json/
Traceback (most recent call last):
  File "C:\nal_adc_support\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\nal_adc_support\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\nal_adc_support\env\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\nal_adc_support\env\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\nal_adc_support\env\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\nal_adc_support\env\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\nal_adc_support\env\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\nal_adc_support\env\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\nal_adc_support\env\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "C:\nal_adc_support\ADC\api\read_source_json_and_write_in_file.py", line 86, in read_json_and_write_in_file
    save_to_file(filter_data(data, bureauCode))
  File "C:\nal_adc_support\ADC\api\read_source_json_and_write_in_file.py", line 64, in save_to_file
    with open(file_name,'w') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\nal_adc_support\\ADC\\stakes\\USDA-ERS-02580.json'
ERROR 2024-04-02 11:10:50,410 basehttp 18036 21444 "GET /api/download-and-read-source-json/ HTTP/1.1" 500 117915
ERROR 2024-04-02 11:11:37,945 log 18848 18148 Internal Server Error: /api/download-and-read-source-json/
Traceback (most recent call last):
  File "C:\nal_adc_support\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\nal_adc_support\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\nal_adc_support\env\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\nal_adc_support\env\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\nal_adc_support\env\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\nal_adc_support\env\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\nal_adc_support\env\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\nal_adc_support\env\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\nal_adc_support\env\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "C:\nal_adc_support\ADC\api\read_source_json_and_write_in_file.py", line 86, in read_json_and_write_in_file
    save_to_file(filter_data(data, bureauCode))
  File "C:\nal_adc_support\ADC\api\read_source_json_and_write_in_file.py", line 64, in save_to_file
    with open(file_name,'w') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\nal_adc_support\\ADC\\stakes\\USDA-ERS-02580.json'
ERROR 2024-04-02 11:11:37,948 basehttp 18848 18148 "GET /api/download-and-read-source-json/ HTTP/1.1" 500 117915
ERROR 2024-04-02 11:13:51,077 log 22952 1836 Internal Server Error: /api/download-and-read-source-json/
Traceback (most recent call last):
  File "C:\nal_adc_support\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\nal_adc_support\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\nal_adc_support\env\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\nal_adc_support\env\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\nal_adc_support\env\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\nal_adc_support\env\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\nal_adc_support\env\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\nal_adc_support\env\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\nal_adc_support\env\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "C:\nal_adc_support\ADC\api\read_source_json_and_write_in_file.py", line 84, in read_json_and_write_in_file
    save_to_file(filter_data(data, bureauCode))
  File "C:\nal_adc_support\ADC\api\read_source_json_and_write_in_file.py", line 62, in save_to_file
    with open(file_name,'w') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\nal_adc_support\\ADC\\stakes\\USDA-ERS-02580.json'
ERROR 2024-04-02 11:13:51,082 basehttp 22952 1836 "GET /api/download-and-read-source-json/ HTTP/1.1" 500 117931
ERROR 2024-04-02 11:14:27,617 log 12244 17460 Internal Server Error: /api/download-and-read-source-json/
Traceback (most recent call last):
  File "C:\nal_adc_support\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\nal_adc_support\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\nal_adc_support\env\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\nal_adc_support\env\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\nal_adc_support\env\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\nal_adc_support\env\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\nal_adc_support\env\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\nal_adc_support\env\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\nal_adc_support\env\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "C:\nal_adc_support\ADC\api\read_source_json_and_write_in_file.py", line 84, in read_json_and_write_in_file
    save_to_file(filter_data(data, bureauCode))
  File "C:\nal_adc_support\ADC\api\read_source_json_and_write_in_file.py", line 62, in save_to_file
    with open(file_name,'w') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\nal_adc_support\\ADC\\stakes\\USDA-ERS-02580.json'
ERROR 2024-04-02 11:14:27,622 basehttp 12244 17460 "GET /api/download-and-read-source-json/ HTTP/1.1" 500 117931
ERROR 2024-04-20 15:02:31,028 log 25136 37664 Internal Server Error: /api/push-to-figshare/
Traceback (most recent call last):
  File "e:\NAL-USDA\economy_research_service\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "e:\NAL-USDA\economy_research_service\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "e:\NAL-USDA\economy_research_service\env\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "e:\NAL-USDA\economy_research_service\env\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "e:\NAL-USDA\economy_research_service\env\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "e:\NAL-USDA\economy_research_service\env\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "e:\NAL-USDA\economy_research_service\env\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "e:\NAL-USDA\economy_research_service\env\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "e:\NAL-USDA\economy_research_service\env\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "E:\NAL-USDA\economy_research_service\api\figshare_mapping.py", line 133, in push_to_figshare
    directory_path = os.path.join(directory_path, file_name)
UnboundLocalError: local variable 'directory_path' referenced before assignment
ERROR 2024-04-20 15:02:31,048 basehttp 25136 37664 "GET /api/push-to-figshare/ HTTP/1.1" 500 103939
ERROR 2024-04-20 15:16:59,400 log 22988 36860 Internal Server Error: /api/push-to-figshare/
Traceback (most recent call last):
  File "e:\NAL-USDA\economy_research_service\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "e:\NAL-USDA\economy_research_service\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "e:\NAL-USDA\economy_research_service\env\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "e:\NAL-USDA\economy_research_service\env\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "e:\NAL-USDA\economy_research_service\env\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "e:\NAL-USDA\economy_research_service\env\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "e:\NAL-USDA\economy_research_service\env\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "e:\NAL-USDA\economy_research_service\env\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "e:\NAL-USDA\economy_research_service\env\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "E:\NAL-USDA\economy_research_service\api\figshare_mapping.py", line 132, in push_to_figshare
    with open(file_name, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'USDA-04708.json'
ERROR 2024-04-20 15:16:59,426 basehttp 22988 36860 "GET /api/push-to-figshare/ HTTP/1.1" 500 104479
ERROR 2024-04-20 15:18:08,980 log 22988 36860 Internal Server Error: /api/push-to-figshare/
Traceback (most recent call last):
  File "e:\NAL-USDA\economy_research_service\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "e:\NAL-USDA\economy_research_service\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "e:\NAL-USDA\economy_research_service\env\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "e:\NAL-USDA\economy_research_service\env\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "e:\NAL-USDA\economy_research_service\env\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "e:\NAL-USDA\economy_research_service\env\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "e:\NAL-USDA\economy_research_service\env\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "e:\NAL-USDA\economy_research_service\env\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "e:\NAL-USDA\economy_research_service\env\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "E:\NAL-USDA\economy_research_service\api\figshare_mapping.py", line 132, in push_to_figshare
    with open(source_file, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'USDA-04708.json'
ERROR 2024-04-20 15:18:08,996 basehttp 22988 36860 "GET /api/push-to-figshare/ HTTP/1.1" 500 104339
